trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
  - script: echo Job1
    displayName: 'Run a one-line script'

  - script: |
      echo blabla
      echo blabla
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2
    displayName: 'Run a one-line script'

  - script: |
      echo blabla
      echo blabla
    displayName: 'Run a multi-line script'
- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Job3
    displayName: 'Run a one-line script'

  - script: |
      echo blabla
      echo blabla
    displayName: 'Run a multi-line script'